name: Publish to GitHub Releases

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and upload
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
      
      - name: Install required packages
        run: pip install -r requirements.txt pyinstaller
      
      - name: Generate executable
        run: pyinstaller --onefile --icon=".github\workflows\app.ico" --add-data="js/*;js" main.py
      
      - name: Extract git info
        id: vars
        shell: bash
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          
          body=""
          for commit in $(git rev-list a68075a133c58152026a3a00f0ac8f97fef417be..HEAD); do
            commit_msg=$(git show -s --no-color --pretty=format:%B $commit)
            sha_short=$(git rev-parse --short $commit)
            
            body+="<img src='.github/workflows/app.ico' width='15' height='15'> "
            body+="[$sha_short](https://github.com/aiden2480/scouts-training-bot/commit/$commit)"
            body+=" - $commit_msg"
            body+=$'\n'
          done

          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}"

          echo "commits_list=$body" >> $GITHUB_OUTPUT

      - name: Upload Release
        uses: svenstaro/upload-release-action@2.7.0          
        with:
          file: dist/main.exe
          asset_name: ScoutsTrainingBot.exe
          release_name: Scouts Training Bot • Release ${{ steps.vars.outputs.sha_short }}
          tag: ${{ steps.vars.outputs.sha_short }}
          body: |
            ${{ steps.vars.outputs.commits_list }}

            Download ScoutsTrainingBot.exe below for windows
