name: Publish to GitHub Releases

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      matrix:
        os: [ windows-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
      
      - name: Install required packages
        run: pip install -r requirements.txt pyinstaller
      
      - name: Generate executable
        run: pyinstaller --onefile --icon=".github\workflows\app.ico" --add-data="js/*;js" main.py
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: dist/${{ matrix.os }}/*
      
  publish:
    name: Publish builds
    needs: build
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: dist/*

      - name: Extract git info
        id: vars
        shell: bash
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "commit_tag=$(git log -n1 --format='%at' | xargs -I{} date -d @{} +%Y-%m-%d-%H-%M-%S)" >> $GITHUB_OUTPUT
          
          body=""
          for commit in $(git rev-list ${{ github.event.before }}..HEAD); do
            commit_msg=$(git show -s --no-color --pretty=format:%B $commit)
            sha_short=$(git rev-parse --short $commit)
            
            body+="<img src='.github/workflows/app.ico' width='15' height='15'> "
            body+="[$sha_short](https://github.com/aiden2480/scouts-training-bot/commit/$commit)"
            body+=" - $commit_msg"
            body+=$'\n'
          done

          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}"

          echo "commits_list=$body" >> $GITHUB_OUTPUT

      - name: Upload Release
        uses: svenstaro/upload-release-action@2.7.0          
        with:
          file: dist/*
          file_glob: true
          release_name: Scouts Training Bot • Release ${{ steps.vars.outputs.sha_short }}
          tag: ${{ steps.vars.outputs.commit_tag }}
          body: |
            ${{ steps.vars.outputs.commits_list }}

            Download ScoutsTrainingBot.exe below for windows
