name: Publish to GitHub Releases

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and upload
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
      
      - name: Install requirements.txt
        run: pip install -r requirements.txt
      
      - name: Install pyinstaller
        run: pip install pyinstaller
      
      - name: Generate executable
        run: pyinstaller --onefile --icon=".github\workflows\app.ico" --add-data="js/*;js" main.py
      
      - name: Extract git info
        id: vars
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          echo "::set-output name=commit_msg::$(git show -s --no-color --pretty=format:%B ${{ github.sha }})"

      - name: Upload Release
        uses: svenstaro/upload-release-action@2.7.0          
        with:
          file: dist/main.exe
          asset_name: ScoutsTrainingBot.exe
          release_name: Scouts Training Bot • ${{ steps.vars.outputs.sha_short }}
          body: |
            [${{ steps.vars.outputs.sha_short }} - ${{ steps.vars.outputs.commit_msg }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }})
